/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.NilaiController;
import java.awt.Point;
import java.awt.event.KeyEvent;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Aries Saifudin
 */
public class FormNilai extends javax.swing.JInternalFrame {
    private final DefaultTableModel nilaiDefaultTableModel;
    private final NilaiController nilaiController = new NilaiController();

    /**
     * Creates new form FormNilai
     */
    public FormNilai() {
        initComponents();
        
        nilaiDefaultTableModel = (DefaultTableModel) nilaiTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mataKuliahPopupMenu = new javax.swing.JPopupMenu();
        tambahMenuItem = new javax.swing.JMenuItem();
        hapusMenuItem = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        tutupButton = new javax.swing.JButton();
        simpanButton = new javax.swing.JButton();
        lihatButton = new javax.swing.JButton();
        nimTextField = new javax.swing.JTextField();
        namaLabel = new javax.swing.JLabel();
        nimLabel = new javax.swing.JLabel();
        kelasTextField = new javax.swing.JTextField();
        nilaiPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nilaiTable = new javax.swing.JTable();
        kelasLabel = new javax.swing.JLabel();
        semesterTextField = new javax.swing.JTextField();
        namaTextField = new javax.swing.JTextField();
        semesterLabel = new javax.swing.JLabel();

        tambahMenuItem.setText("Tambah");
        tambahMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahMenuItemActionPerformed(evt);
            }
        });
        mataKuliahPopupMenu.add(tambahMenuItem);

        hapusMenuItem.setText("Hapus");
        hapusMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusMenuItemActionPerformed(evt);
            }
        });
        mataKuliahPopupMenu.add(hapusMenuItem);

        setClosable(true);
        setTitle("Mengelola Nilai Mahasiswa");

        tutupButton.setText("Tutup");
        tutupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutupButtonActionPerformed(evt);
            }
        });

        simpanButton.setText("Simpan");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        lihatButton.setText("Lihat");
        lihatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatButtonActionPerformed(evt);
            }
        });

        nimTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nimTextFieldKeyPressed(evt);
            }
        });

        namaLabel.setText("Nama");

        nimLabel.setText("NIM");

        kelasTextField.setEditable(false);

        nilaiPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Nilai"));

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseReleased(evt);
            }
        });

        nilaiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama Mata Kuliah", "Tugas", "UTS", "UAS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        nilaiTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        nilaiTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nilaiTableMouseReleased(evt);
            }
        });
        nilaiTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                nilaiTablePropertyChange(evt);
            }
        });
        nilaiTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nilaiTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(nilaiTable);
        if (nilaiTable.getColumnModel().getColumnCount() > 0) {
            nilaiTable.getColumnModel().getColumn(0).setMinWidth(90);
            nilaiTable.getColumnModel().getColumn(0).setPreferredWidth(90);
            nilaiTable.getColumnModel().getColumn(0).setMaxWidth(90);
            nilaiTable.getColumnModel().getColumn(2).setMinWidth(70);
            nilaiTable.getColumnModel().getColumn(2).setPreferredWidth(70);
            nilaiTable.getColumnModel().getColumn(2).setMaxWidth(70);
            nilaiTable.getColumnModel().getColumn(3).setMinWidth(70);
            nilaiTable.getColumnModel().getColumn(3).setPreferredWidth(70);
            nilaiTable.getColumnModel().getColumn(3).setMaxWidth(70);
            nilaiTable.getColumnModel().getColumn(4).setMinWidth(70);
            nilaiTable.getColumnModel().getColumn(4).setPreferredWidth(70);
            nilaiTable.getColumnModel().getColumn(4).setMaxWidth(70);
        }

        javax.swing.GroupLayout nilaiPanelLayout = new javax.swing.GroupLayout(nilaiPanel);
        nilaiPanel.setLayout(nilaiPanelLayout);
        nilaiPanelLayout.setHorizontalGroup(
            nilaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        nilaiPanelLayout.setVerticalGroup(
            nilaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        kelasLabel.setText("Kelas");

        semesterTextField.setEditable(false);

        namaTextField.setEditable(false);

        semesterLabel.setText("Semester");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(namaLabel)
                    .addComponent(nimLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lihatButton))
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kelasLabel)
                    .addComponent(semesterLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(semesterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kelasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(simpanButton, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(tutupButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nilaiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nimLabel)
                        .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lihatButton)
                        .addComponent(semesterLabel)
                        .addComponent(semesterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(simpanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kelasLabel)
                    .addComponent(kelasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tutupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(nilaiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setNim(String nim){
        nimTextField.setText(nim);
    }
    
    public void setNama(String nama){
        namaTextField.setText(nama);
    }
    
    public void setSemester(String semester){
	semesterTextField.setText(semester);
    }
    
    public void setKelas(String kelas){
	kelasTextField.setText(kelas);
    }
    
    public void setNamaMataKuliah(String nama){
	nilaiTable.setValueAt(nama, nilaiTable.getSelectedRow(), 1);
    }
    
    public void hapusNilai(){
        for (int i=2; i<=4; i++){
            nilaiTable.setValueAt("", nilaiTable.getSelectedRow(), i);
        }
    }
    
    public void setTambahNilai(Object[] nilaiMatakuliah){
        int noRecord;
        
        if ((noRecord = nilaiDefaultTableModel.getRowCount()-1) >= 0){
            while ((((nilaiTable.getValueAt(noRecord, 0) == null) || nilaiTable.getValueAt(noRecord, 0).equals("")) && (noRecord > 0))){
                noRecord--;
            }
            
            if (!((nilaiTable.getValueAt(noRecord, 0) == null) || nilaiTable.getValueAt(noRecord, 0).equals(""))){
                noRecord++;
            }
            
            if (noRecord < nilaiDefaultTableModel.getRowCount()){
                if ((nilaiTable.getValueAt(noRecord, 0) == null) || nilaiTable.getValueAt(noRecord, 0).equals("")){
                    nilaiDefaultTableModel.removeRow(noRecord--);
                }
            } else {
                noRecord--;
            }
        }
        
        nilaiDefaultTableModel.insertRow(++noRecord, nilaiMatakuliah);
    }
    
    public void clearNilaiTable(){
        nilaiDefaultTableModel.setRowCount(0);
    }
    
    private void klikKananTabel(java.awt.event.MouseEvent evt){
        if(evt.isPopupTrigger()){
            mataKuliahPopupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }
    
    private void tutupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutupButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_tutupButtonActionPerformed

    private void nilaiTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nilaiTableMouseReleased
        // TODO add your handling code here:
        Point p = evt.getPoint();
        int rowNumber = nilaiTable.rowAtPoint( p );
        ListSelectionModel model = nilaiTable.getSelectionModel();
        model.setSelectionInterval( rowNumber, rowNumber );
        
        klikKananTabel(evt);
    }//GEN-LAST:event_nilaiTableMouseReleased

    private void jScrollPane1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseReleased
        // TODO add your handling code here:
        klikKananTabel(evt);
    }//GEN-LAST:event_jScrollPane1MouseReleased

    private void nilaiTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nilaiTableKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (nilaiTable.getSelectedRow() == (nilaiTable.getRowCount()-1)){
                if (nilaiTable.getSelectedColumn()==0){
                    nilaiDefaultTableModel.insertRow( nilaiDefaultTableModel.getRowCount(), new Object[]{}); 
                } else {
                    if (nilaiTable.getSelectedColumn() == (nilaiTable.getColumnCount()-1)){
                        nilaiDefaultTableModel.insertRow( nilaiDefaultTableModel.getRowCount(), new Object[]{});
                        nilaiTable.changeSelection(nilaiTable.getSelectedRow(), 0, false, false);
                    } else {
                        nilaiTable.changeSelection(nilaiTable.getSelectedRow()-1, nilaiTable.getSelectedColumn()+1, false, false);                    
                    }
                }
            } else {
                if (nilaiTable.getSelectedColumn() == (nilaiTable.getColumnCount()-1)){
                    nilaiTable.changeSelection(nilaiTable.getSelectedRow(), 0, false, false);
                } else {
                    nilaiTable.setColumnSelectionInterval(nilaiTable.getSelectedColumn()+1,nilaiTable.getSelectedColumn()+1);
                    nilaiTable.setRowSelectionInterval(nilaiTable.getSelectedRow()-1,nilaiTable.getSelectedRow()-1);
                }
            }
        }
    }//GEN-LAST:event_nilaiTableKeyPressed

    private void nilaiTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_nilaiTablePropertyChange
        // TODO add your handling code here:
        if (nilaiTable.getSelectedRowCount()>0){
            if (nilaiTable.getSelectedColumn()==0){
                String kodeMataKuliah = "";
                try{
                    kodeMataKuliah = nilaiTable.getValueAt(nilaiTable.getSelectedRow(), 0).toString();                
		}catch (Exception ex){}
                
		if (!kodeMataKuliah.equals("")){
                    nilaiController.cariMataKuliah(kodeMataKuliah); 	            
		}
            }
        }
    }//GEN-LAST:event_nilaiTablePropertyChange

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        // TODO add your handling code here:
        nilaiController.simpan(nimTextField, nilaiTable);
    }//GEN-LAST:event_simpanButtonActionPerformed

    private void lihatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatButtonActionPerformed
        // TODO add your handling code here:
        nilaiController.tampilkanFormLihatMahasiswa();
    }//GEN-LAST:event_lihatButtonActionPerformed

    private void nimTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nimTextFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            nilaiController.cariMahasiswa(nimTextField);
        }
    }//GEN-LAST:event_nimTextFieldKeyPressed

    private void tambahMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahMenuItemActionPerformed
        // TODO add your handling code here:
        nilaiController.tampilkanFormLihatMataKuliah();
    }//GEN-LAST:event_tambahMenuItemActionPerformed

    private void hapusMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusMenuItemActionPerformed
        // TODO add your handling code here:
        if (nilaiTable.getSelectedRowCount() > 0){
            nilaiDefaultTableModel.removeRow(
                    nilaiTable.getSelectedRow());
        }
    }//GEN-LAST:event_hapusMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem hapusMenuItem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kelasLabel;
    private javax.swing.JTextField kelasTextField;
    private javax.swing.JButton lihatButton;
    private javax.swing.JPopupMenu mataKuliahPopupMenu;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JPanel nilaiPanel;
    private javax.swing.JTable nilaiTable;
    private javax.swing.JLabel nimLabel;
    private javax.swing.JTextField nimTextField;
    private javax.swing.JLabel semesterLabel;
    private javax.swing.JTextField semesterTextField;
    private javax.swing.JButton simpanButton;
    private javax.swing.JMenuItem tambahMenuItem;
    private javax.swing.JButton tutupButton;
    // End of variables declaration//GEN-END:variables
}
